# Generated by Django 5.2.6 on 2026-04-28 15:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinapseServiceSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sinapse_service_id', models.CharField(max_length=100, unique=True)),
                ('source_table', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_payload', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status_sync', models.CharField(choices=[('SYNCED', 'Sincronizado'), ('DIVERGENT', 'Divergente'), ('ERROR', 'Erro')], default='SYNCED', max_length=20)),
                ('divergencia', models.TextField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_sync_at'],
                'indexes': [models.Index(fields=['status_sync'], name='integration_status__6da618_idx'), models.Index(fields=['last_sync_at'], name='integration_last_sy_91e8b1_idx')],
            },
        ),
    ]
