# Generated by Django 5.2.6 on 2026-04-28 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_demanda_data_criacao'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinapseServicoMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sinapse_service_id', models.CharField(max_length=100, unique=True)),
                ('match_status', models.CharField(choices=[('AUTO', 'Auto mapeado'), ('MANUAL', 'Mapeado manualmente'), ('UNMATCHED', 'Sem correspondencia')], default='UNMATCHED', max_length=20)),
                ('match_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servico_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinapse_mapeamentos', to='core.servico')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['match_status'], name='integration_match_s_8382b7_idx'), models.Index(fields=['last_seen_at'], name='integration_last_se_c986e1_idx')],
            },
        ),
    ]
