# Generated by Django 5.2.6 on 2026-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_sinapseservicomap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinapseservicomap',
            name='last_manual_actor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sinapseservicomap',
            name='last_manual_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
