# Generated by Django 5.2.7 on 2026-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_sinapseservicomap_last_manual_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=255)),
                ('css', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'catalog_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogOrgao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('nome', models.CharField(max_length=255)),
                ('tipo_orgao', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'catalog_orgao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogPublico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('is_default', models.BooleanField()),
            ],
            options={
                'db_table': 'catalog_publico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogServico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField()),
                ('descricao_html', models.TextField()),
                ('departamento', models.TextField(blank=True, null=True)),
                ('telefone', models.JSONField(blank=True, null=True)),
                ('email', models.JSONField(blank=True, null=True)),
                ('agendamento', models.TextField()),
                ('solicitacao_internet', models.CharField(max_length=200)),
                ('solicitacao_perfil', models.TextField()),
                ('atendimento_dia_hora', models.TextField()),
                ('documentos_necessarios', models.TextField()),
                ('prazo', models.TextField(blank=True, null=True)),
                ('requisitos_html', models.TextField()),
                ('fluxo_html', models.TextField()),
                ('observacoes_html', models.TextField()),
                ('status', models.IntegerField()),
                ('texto_limpo_rag', models.TextField()),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogTipoatendimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'catalog_tipoatendimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogUnidadeAdministrativa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('arquivo_imagem', models.CharField(max_length=255)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('texto_limpo_rag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_unidadeadministrativa',
                'managed': False,
            },
        ),
    ]
