# Generated by Django 5.2.6 on 2026-05-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_remove_sinapseservicomap_servico_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogorgao',
            options={'managed': False, 'verbose_name': 'órgão (Sinapse)', 'verbose_name_plural': 'órgãos (Sinapse)'},
        ),
        migrations.AlterModelOptions(
            name='catalogservico',
            options={'managed': False, 'verbose_name': 'serviço — carta (Sinapse)', 'verbose_name_plural': 'serviços — carta (Sinapse)'},
        ),
        migrations.AlterModelOptions(
            name='catalogunidadeadministrativa',
            options={'managed': False, 'verbose_name': 'unidade administrativa (Sinapse)', 'verbose_name_plural': 'unidades administrativas (Sinapse)'},
        ),
    ]
