# Generated by Django 5.2.7 on 2025-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo',
            field=models.CharField(choices=[('EVENTO', 'Evento'), ('ATENDIMENTO', 'Atendimento'), ('SERVIÇO', 'Serviço'), ('VISTORIA', 'Vistoria'), ('IMPLANTAÇÃO', 'Implantação')], default='SERVIÇO', max_length=20),
        ),
    ]
