# Generated by Django 5.2.7 on 2025-10-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demanda_bairro_demanda_cep_demanda_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='endereco',
        ),
    ]
