# Generated by Django 5.2.7 on 2025-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_demanda_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('aguardando_protocolo', 'Aguardando Protocolo'), ('protocolado', 'Protocolado e Despachado'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='RASCUNHO', max_length=30),
        ),
    ]
