# Generated by Django 5.2.7 on 2025-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_demanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='protocolo_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
