# Generated by Django 5.2.7 on 2025-10-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_demanda_protocolo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('VEREADOR', 'Vereador'), ('PROTOCOLO', 'Protocolo'), ('SECRETARIA', 'Secretaria'), ('GESTOR', 'Gestor')], max_length=20, null=True),
        ),
    ]
