# Generated by Django 5.2.7 on 2025-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_demanda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='protocolo_interno',
        ),
        migrations.AddField(
            model_name='demanda',
            name='protocolo_executivo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='protocolo_legislativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
