# Generated by Django 5.2.7 on 2025-10-14 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicodemanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENVIO_OFICIAL', 'Envio Oficial'), ('DESPACHO', 'Despacho para Secretaria'), ('STATUS_UPDATE', 'Atualização de Status'), ('COMENTARIO', 'Comentário'), ('ANALISE_TECNICA', 'Análise Técnica'), ('ATRASO', 'Registro de Atraso'), ('CONCLUSAO', 'Conclusão do Serviço')], max_length=20)),
                ('descricao', models.TextField(help_text='Descrição detalhada do passo, justificativa do atraso, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='core.demanda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnexoTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_tramitacao/%Y/%m/%d/')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.tramitacao')),
            ],
        ),
    ]
