# Generated by Django 5.2.7 on 2025-10-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tramitacao_anexotramitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoDemanda',
        ),
    ]
