# Generated by Django 5.2.7 on 2025-10-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_demanda_latitude_demanda_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.secretaria'),
        ),
    ]
