# Generated by Django 5.2.7 on 2025-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_PROTOCOLO', 'Aguardando Protocolo'), ('PROTOCOLADO', 'Protocolado e Despachado'), ('EM_EXECUCAO', 'Em Execução'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('AGUARDANDO_TRANSFERENCIA', 'Aguardando Transferência')], default='RASCUNHO', max_length=30),
        ),
    ]
