# Generated by Django 5.2.7 on 2025-10-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_demanda_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramitacao',
            old_name='usuario',
            new_name='responsavel',
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo',
            field=models.CharField(choices=[('ENVIO_OFICIAL', 'Envio Oficial'), ('DESPACHO', 'Despacho para Secretaria'), ('STATUS_UPDATE', 'Atualização de Status'), ('COMENTARIO', 'Comentário'), ('ANALISE_TECNICA', 'Análise Técnica'), ('ATRASO', 'Registro de Atraso'), ('CONCLUSAO', 'Conclusão do Serviço'), ('TRANSFERENCIA', 'Transferência de Setor/Secretaria')], max_length=20),
        ),
    ]
