# Generated by Django 5.2.7 on 2025-10-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_usuario_tramitacao_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='tipo',
            field=models.CharField(choices=[('ENVIO_OFICIAL', 'Envio Oficial'), ('DESPACHO', 'Despacho para Secretaria'), ('STATUS_UPDATE', 'Atualização de Status'), ('COMENTARIO', 'Comentário'), ('ANALISE_TECNICA', 'Análise Técnica'), ('ATRASO', 'Registro de Atraso'), ('PROGRAMACAO', 'Programação do Serviço'), ('CONCLUSAO', 'Conclusão do Serviço'), ('TRANSFERENCIA', 'Transferência de Setor/Secretaria')], max_length=20),
        ),
    ]
