# Generated by Django 5.2.7 on 2025-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_usuario_avatar_usuario_cargo_usuario_ramal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='assinatura',
            field=models.TextField(blank=True, help_text='Texto que aparecerá como assinatura. Ex: Nome Completo, Cargo, Secretaria.', null=True),
        ),
    ]
