# Generated by Django 5.2.7 on 2025-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='prazo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
