# Generated by Django 5.2.7 on 2025-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_servico_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='prazo',
            field=models.IntegerField(blank=True, help_text='Prazo para execução do serviço em dias.', null=True),
        ),
    ]
