# Generated by Django 5.2.7 on 2025-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_update_prazo_padrao_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_inicio_prazo',
            field=models.DateTimeField(blank=True, help_text="Data em que o status mudou para 'Protocolado', iniciando a contagem do prazo.", null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='notificacao_atraso_enviada',
            field=models.BooleanField(default=False, help_text='Marca se a notificação de atraso já foi enviada.'),
        ),
    ]
