# Generated by Django 5.2.7 on 2025-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_demanda_data_inicio_prazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('NOVO_OFICIO', 'Novo Ofício'), ('DESPACHO', 'Despacho'), ('ATUALIZACAO', 'Atualização'), ('TRANSFERENCIA', 'Transferência'), ('CONCLUSAO', 'Conclusão'), ('ATRASO', 'Atraso')], default='ATUALIZACAO', max_length=20),
        ),
    ]
