# Generated by Django 5.2.7 on 2025-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link para o processo no sistema externo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='numero_externo',
            field=models.CharField(blank=True, help_text='Número do processo em outro sistema (ex: 1Doc, SEI)', max_length=100, null=True),
        ),
    ]
