# Generated by Django 5.2.7 on 2025-11-10 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_demanda_link_externo_demanda_numero_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
