# Generated by Django 5.2.7 on 2026-05-13 13:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_demanda_data_criacao'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ClusterExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_resumo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=50)),
                ('secretaria_responsavel', models.CharField(blank=True, max_length=150)),
                ('bairro_referencia', models.CharField(blank=True, max_length=100)),
                ('centroide', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='demanda',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ia_categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ia_processado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demanda',
            name='ia_sentimento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='demanda',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to='core.clusterexecucao'),
        ),
    ]
