# Generated by Django 5.2.6 on 2026-05-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_demanda_sinapse_servico_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='core_chatse_autor_i_befdf5_idx',
            old_name='chatsession_autor_upd',
        ),
    ]
