# Generated by Django 5.2.6 on 2026-05-19 17:13

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_chatsessaoanexo_indice_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='origem_vinculo',
            field=models.CharField(choices=[('CARTA', 'Carta de serviços'), ('TENDENCIA', 'Tendência (fora da carta)')], default='CARTA', help_text='Trilha de vinculação ao protocolar (carta Sinapse ou tendência interna).', max_length=16),
        ),
        migrations.AlterField(
            model_name='chatsessaoanexo',
            name='indice_demanda',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Demanda do rascunho (0-based) à qual o arquivo se refere.', null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='demandas_rascunho',
            field=models.JSONField(blank=True, default=list, help_text='Lista de dicts com rascunhos (titulo, descricao, endereco, sinapse_servico_id_sugerido, ...).'),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='destinatario_nome',
            field=models.CharField(default='Mara Bertaiolli', help_text='Nome da autoridade destinatária do ofício.', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='destinatario_tratamento',
            field=models.CharField(default='Excelentíssima Senhora Prefeita Municipal', help_text='Tratamento formal (ex.: Excelentíssima Senhora Prefeita Municipal).', max_length=80),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='municipio',
            field=models.CharField(default='Mogi das Cruzes', help_text='Cidade usada no cabeçalho e na data do ofício.', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='texto_abertura',
            field=models.TextField(blank=True, help_text='Parágrafo opcional após a saudação. Use {municipio} se quiser referenciar a cidade.'),
        ),
        migrations.CreateModel(
            name='Tendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto_canonico', models.TextField(blank=True, help_text='Texto usado para gerar/atualizar o embedding (problema + contexto).')),
                ('descricao_resumo', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('VINCULADA_CARTA', 'Vinculada à carta'), ('ARQUIVADA', 'Arquivada')], default='ABERTA', max_length=24)),
                ('sinapse_orgao_id', models.BigIntegerField(blank=True, help_text='Órgão provável até promoção na carta ou análise do Protocolo.', null=True)),
                ('sinapse_servico_id', models.BigIntegerField(blank=True, help_text='Preenchido quando a tendência for promovida a serviço na carta.', null=True)),
                ('volume_total', models.PositiveIntegerField(default=0)),
                ('primeira_ocorrencia', models.DateTimeField(auto_now_add=True)),
                ('ultima_ocorrencia', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendencias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-volume_total', '-ultima_ocorrencia'],
            },
        ),
        migrations.AddField(
            model_name='demanda',
            name='tendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to='core.tendencia'),
        ),
        migrations.CreateModel(
            name='TendenciaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_demanda', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_triagem_max', models.FloatField(blank=True, help_text='Maior score Sinapse na triagem desta ocorrência (se houver).', null=True)),
                ('texto_origem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_tendencia', to='core.demanda')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_tendencia', to='core.chatsession')),
                ('tendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.tendencia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='tendencia',
            index=models.Index(fields=['status', '-volume_total'], name='core_tenden_status_f9c909_idx'),
        ),
        migrations.AddIndex(
            model_name='tendencia',
            index=models.Index(fields=['slug'], name='core_tenden_slug_5e7741_idx'),
        ),
        migrations.AddIndex(
            model_name='tendenciaocorrencia',
            index=models.Index(fields=['tendencia', '-criado_em'], name='core_tenden_tendenc_523c55_idx'),
        ),
    ]
