# Generated by Django 5.2.6 on 2026-05-22 14:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_clusterexecucao_despacho_super_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasOtimizacaoCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência para as estatísticas', unique=True)),
                ('total_servicos_carta', models.PositiveIntegerField(default=0, help_text='Total de serviços na carta Sinapse')),
                ('total_servicos_otimizados', models.PositiveIntegerField(default=0, help_text='Total de serviços com otimizações aplicadas')),
                ('total_servicos_necessitam_revisao', models.PositiveIntegerField(default=0, help_text='Total de serviços que necessitam revisão manual')),
                ('score_qualidade_medio_anterior', models.DecimalField(blank=True, decimal_places=1, help_text='Score médio antes das otimizações', max_digits=3, null=True)),
                ('score_qualidade_medio_atual', models.DecimalField(blank=True, decimal_places=1, help_text='Score médio após as otimizações', max_digits=3, null=True)),
                ('servicos_com_html_residual', models.PositiveIntegerField(default=0, help_text='Serviços com problemas de HTML')),
                ('servicos_prazo_nao_estruturado', models.PositiveIntegerField(default=0, help_text='Serviços com prazos não estruturados')),
                ('servicos_titulo_tecnico', models.PositiveIntegerField(default=0, help_text='Serviços com títulos muito técnicos')),
                ('total_otimizacoes_aplicadas', models.PositiveIntegerField(default=0, help_text='Total de otimizações aplicadas no período')),
                ('otimizacoes_por_tipo', models.JSONField(blank=True, default=dict, help_text='Contadores por tipo de otimização')),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('tempo_processamento_minutos', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo total de processamento em minutos', max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Estatística de Otimização da Carta',
                'verbose_name_plural': 'Estatísticas de Otimização da Carta',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOtimizacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_otimizacao', models.CharField(choices=[('limpeza_html', 'Limpeza de HTML'), ('estruturacao_prazo', 'Estruturação de Prazo'), ('extracao_palavras_chave', 'Extração de Palavras-chave'), ('inferencia_problemas', 'Inferência de Problemas'), ('otimizacao_embedding', 'Otimização de Embedding'), ('revisao_manual', 'Revisão Manual'), ('correcao_automatica', 'Correção Automática')], max_length=32)),
                ('descricao_mudanca', models.TextField(help_text='Descrição detalhada da mudança aplicada')),
                ('dados_antes', models.JSONField(blank=True, help_text='Estado antes da otimização (para rollback)', null=True)),
                ('dados_depois', models.JSONField(blank=True, help_text='Estado depois da otimização', null=True)),
                ('score_qualidade_antes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_qualidade_depois', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aplicado_automaticamente', models.BooleanField(default=True, help_text='Se foi aplicado automaticamente ou por intervenção manual')),
                ('timestamp_aplicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Otimização',
                'verbose_name_plural': 'Históricos de Otimizações',
                'ordering': ['-timestamp_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoMetadataRico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinapse_servico_id', models.BigIntegerField(help_text='ID do serviço na carta Sinapse (chave estrangeira)', unique=True)),
                ('tipo_processo', models.CharField(blank=True, choices=[('administrativo_simples', 'Administrativo Simples'), ('administrativo_licenca', 'Administrativo com Licenciamento'), ('operacional_vistoria', 'Operacional com Vistoria'), ('digital_automatizado', 'Digital Automatizado'), ('terceirizado', 'Terceirizado/Parceria'), ('hibrido', 'Híbrido (Digital + Presencial)')], help_text='Tipo de processo inferido automaticamente', max_length=32, null=True)),
                ('publico_alvo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cidadaos', 'Cidadãos em Geral'), ('empresarios', 'Empresários'), ('servidores_publicos', 'Servidores Públicos'), ('profissionais_liberais', 'Profissionais Liberais'), ('organizacoes', 'Organizações/Entidades'), ('especifico', 'Público Específico')], max_length=32), blank=True, default=list, help_text='Público(s) alvo identificado(s)', size=5)),
                ('canal_preferencial', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('digital', 'Digital/Online'), ('telefone', 'Telefone'), ('hibrido', 'Híbrido'), ('terceirizado', 'Terceirizado')], help_text='Canal preferencial inferido', max_length=16, null=True)),
                ('prazo_dias_numericos', models.PositiveIntegerField(blank=True, help_text='Prazo em dias (extraído do texto livre)', null=True)),
                ('prazo_categoria', models.CharField(choices=[('IMEDIATO', 'Imediato (0 dias)'), ('RAPIDO', 'Rápido (1-5 dias)'), ('NORMAL', 'Normal (6-30 dias)'), ('LONGO', 'Longo (31+ dias)'), ('INDEFINIDO', 'Indefinido/Variável')], default='INDEFINIDO', help_text='Categoria do prazo estruturada', max_length=16)),
                ('prazo_observacoes', models.TextField(blank=True, help_text='Observações sobre o prazo (texto original ou exceções)')),
                ('problemas_resolve', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Lista de problemas que o serviço resolve (linguagem cidadã)', size=5)),
                ('palavras_chave_expandidas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Palavras-chave + sinônimos para melhorar busca', size=20)),
                ('contexto_uso_estruturado', models.JSONField(blank=True, default=dict, help_text='Contexto de uso estruturado (quando, quem, onde)')),
                ('score_qualidade_texto', models.PositiveSmallIntegerField(default=5, help_text='Score de qualidade do texto RAG (1-10)')),
                ('tem_problemas_html', models.BooleanField(default=False, help_text='Indica se havia problemas de HTML no texto original')),
                ('necessita_revisao', models.BooleanField(default=False, help_text='Indica se necessita revisão manual')),
                ('dependencias_internas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Dependências internas identificadas (outros setores, aprovações)', size=10)),
                ('documentos_estruturados', models.JSONField(blank=True, default=dict, help_text='Documentos necessários estruturados (obrigatórios/opcionais)')),
                ('custo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Estimativa de horas de trabalho interno', max_digits=5, null=True)),
                ('versao_otimizacao', models.PositiveIntegerField(default=1, help_text='Versão da otimização aplicada')),
                ('texto_rag_otimizado', models.TextField(blank=True, help_text='Texto otimizado para RAG (backup local)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('otimizado_por_ia_em', models.DateTimeField(blank=True, help_text='Última otimização por IA', null=True)),
                ('revisado_manualmente_em', models.DateTimeField(blank=True, help_text='Última revisão manual', null=True)),
            ],
            options={
                'verbose_name': 'Metadado Rico de Serviço',
                'verbose_name_plural': 'Metadados Ricos de Serviços',
            },
        ),
        migrations.RenameIndex(
            model_name='copilotofaqorientacao',
            new_name='core_copilo_ativo_6f972d_idx',
            old_name='core_copilo_ativo_i_6e8f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='copilotofaqorientacao',
            new_name='core_copilo_municip_27e3a0_idx',
            old_name='core_copilo_municip_2a1b9c_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='assinatura',
            field=models.TextField(blank=True, help_text='Texto/HTML exibido na assinatura do ofício quando não houver imagem.', null=True),
        ),
        migrations.AddField(
            model_name='historicootimizacaoservico',
            name='usuario_aplicou',
            field=models.ForeignKey(blank=True, help_text='Usuário que aplicou manualmente (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicometadatarico',
            index=models.Index(fields=['sinapse_servico_id'], name='core_servic_sinapse_7a8f33_idx'),
        ),
        migrations.AddIndex(
            model_name='servicometadatarico',
            index=models.Index(fields=['tipo_processo'], name='core_servic_tipo_pr_78d2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicometadatarico',
            index=models.Index(fields=['prazo_categoria'], name='core_servic_prazo_c_1ccaae_idx'),
        ),
        migrations.AddIndex(
            model_name='servicometadatarico',
            index=models.Index(fields=['score_qualidade_texto'], name='core_servic_score_q_911d67_idx'),
        ),
        migrations.AddIndex(
            model_name='servicometadatarico',
            index=models.Index(fields=['-atualizado_em'], name='core_servic_atualiz_7446dd_idx'),
        ),
        migrations.AddField(
            model_name='historicootimizacaoservico',
            name='servico_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_otimizacoes', to='core.servicometadatarico'),
        ),
        migrations.AddIndex(
            model_name='historicootimizacaoservico',
            index=models.Index(fields=['servico_metadata', '-timestamp_aplicacao'], name='core_histor_servico_a41848_idx'),
        ),
        migrations.AddIndex(
            model_name='historicootimizacaoservico',
            index=models.Index(fields=['tipo_otimizacao'], name='core_histor_tipo_ot_0d256a_idx'),
        ),
    ]
