# Generated by Django 5.2.6 on 2026-05-22 14:24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_carta_metadata_ricos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasBaseOtimizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Data de referência das estatísticas', unique=True)),
                ('total_servicos_sinapse', models.PositiveIntegerField(default=0, help_text='Total de serviços na base Sinapse')),
                ('total_servicos_otimizados', models.PositiveIntegerField(default=0, help_text='Total de serviços na base otimizada')),
                ('total_validados_humano', models.PositiveIntegerField(default=0, help_text='Total validados por humanos')),
                ('total_precisam_revisao', models.PositiveIntegerField(default=0, help_text='Total que precisam de revisão')),
                ('score_medio_original', models.DecimalField(blank=True, decimal_places=1, help_text='Score médio original', max_digits=3, null=True)),
                ('score_medio_otimizado', models.DecimalField(blank=True, decimal_places=1, help_text='Score médio otimizado', max_digits=3, null=True)),
                ('melhoria_media', models.DecimalField(blank=True, decimal_places=1, help_text='Melhoria média nos scores', max_digits=3, null=True)),
                ('problemas_html_residual', models.PositiveIntegerField(default=0)),
                ('problemas_prazo_estruturado', models.PositiveIntegerField(default=0)),
                ('problemas_titulo_tecnico', models.PositiveIntegerField(default=0)),
                ('problemas_entidades_html', models.PositiveIntegerField(default=0)),
                ('processos_administrativo', models.PositiveIntegerField(default=0)),
                ('processos_operacional', models.PositiveIntegerField(default=0)),
                ('processos_equipamentos', models.PositiveIntegerField(default=0)),
                ('processos_misto', models.PositiveIntegerField(default=0)),
                ('processos_terceirizado', models.PositiveIntegerField(default=0)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('tempo_processamento', models.DurationField(blank=True, help_text='Tempo para gerar as estatísticas', null=True)),
            ],
            options={
                'verbose_name': 'Estatísticas Base Otimizada',
                'verbose_name_plural': 'Estatísticas Base Otimizada',
                'db_table': 'core_estatisticas_base_otimizada',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ServicoOtimizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinapse_servico_id', models.PositiveIntegerField(help_text='ID do serviço original no Sinapse', unique=True)),
                ('titulo_otimizado', models.CharField(help_text='Título limpo e orientado ao cidadão', max_length=200)),
                ('descricao_objetiva', models.TextField(help_text='Descrição clara sem HTML, linguagem acessível')),
                ('intencao_servico', models.TextField(blank=True, help_text='Para que serve este serviço (1-2 frases)')),
                ('problemas_resolve', models.JSONField(default=list, help_text='Lista dos problemas/situações que este serviço resolve')),
                ('texto_rag_otimizado', models.TextField(help_text='Texto concatenado e estruturado para embedding')),
                ('embedding_otimizado', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Vetor 1024d gerado do texto otimizado', null=True)),
                ('tipo_processo', models.CharField(blank=True, choices=[('ADMINISTRATIVO', 'Apenas Administrativo'), ('OPERACIONAL', 'Operacional'), ('EQUIPAMENTOS', 'Depende de Equipamentos'), ('MISTO', 'Administrativo + Operacional'), ('TERCEIRIZADO', 'Terceirizado')], help_text='Tipo de processo envolvido', max_length=20)),
                ('prazo_dias', models.PositiveIntegerField(blank=True, help_text='Prazo em dias (estruturado)', null=True)),
                ('prazo_categoria', models.CharField(blank=True, choices=[('IMEDIATO', 'Imediato'), ('RAPIDO', 'Rápido (até 7 dias)'), ('NORMAL', 'Normal (até 30 dias)'), ('LONGO', 'Longo (mais de 30 dias)'), ('VARIAVEL', 'Variável')], help_text='Categoria do prazo', max_length=15)),
                ('prazo_observacoes', models.TextField(blank=True, help_text='Observações sobre o prazo')),
                ('dependencias_documentos', models.JSONField(default=list, help_text='Lista estruturada de documentos necessários')),
                ('dependencias_realizacao', models.JSONField(default=list, help_text='Pré-requisitos para realização do serviço')),
                ('dependencias_pagamentos', models.JSONField(default=list, help_text='Informações sobre taxas e pagamentos')),
                ('palavras_chave', models.JSONField(default=list, help_text='Palavras-chave e sinônimos para busca semântica')),
                ('score_qualidade_original', models.PositiveSmallIntegerField(default=1, help_text='Score de qualidade do serviço original (1-10)')),
                ('score_qualidade_otimizado', models.PositiveSmallIntegerField(default=5, help_text='Score de qualidade após otimização (1-10)')),
                ('problemas_identificados', models.JSONField(default=list, help_text='Lista de problemas encontrados no serviço original')),
                ('melhorias_aplicadas', models.JSONField(default=list, help_text='Lista de melhorias aplicadas na otimização')),
                ('versao_otimizacao', models.CharField(default='1.0', help_text='Versão do algoritmo de otimização usado', max_length=10)),
                ('otimizado_em', models.DateTimeField(auto_now_add=True, help_text='Data/hora da otimização')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Última atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Se o serviço otimizado está ativo')),
                ('validado_humano', models.BooleanField(default=False, help_text='Se passou por validação humana')),
                ('precisa_revisao', models.BooleanField(default=False, help_text='Se necessita revisão manual')),
            ],
            options={
                'verbose_name': 'Serviço Otimizado',
                'verbose_name_plural': 'Serviços Otimizados',
                'db_table': 'core_servico_otimizado',
                'indexes': [models.Index(fields=['sinapse_servico_id'], name='core_servic_sinapse_a6d73e_idx'), models.Index(fields=['score_qualidade_otimizado'], name='core_servic_score_q_dbd12c_idx'), models.Index(fields=['tipo_processo'], name='core_servic_tipo_pr_f7ebcc_idx'), models.Index(fields=['prazo_categoria'], name='core_servic_prazo_c_4e7147_idx'), models.Index(fields=['ativo', 'validado_humano'], name='core_servic_ativo_de57ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogOtimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ATUALIZACAO', 'Atualização'), ('VALIDACAO', 'Validação Humana'), ('REVISAO', 'Revisão'), ('DESATIVACAO', 'Desativação')], help_text='Tipo de operação realizada', max_length=20)),
                ('detalhes', models.JSONField(default=dict, help_text='Detalhes da operação (scores, problemas, etc.)')),
                ('usuario', models.CharField(default='sistema', help_text='Usuário responsável pela operação', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data/hora da operação')),
                ('servico_otimizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.servicootimizado')),
            ],
            options={
                'verbose_name': 'Log de Otimização',
                'verbose_name_plural': 'Logs de Otimização',
                'db_table': 'core_log_otimizacao',
                'ordering': ['-timestamp'],
            },
        ),
    ]
