# Generated by Django 5.2.6 on 2026-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_base_otimizada_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicootimizado',
            name='link_sistema',
            field=models.URLField(blank=True, help_text='Link direto para o sistema de solicitação'),
        ),
        migrations.AddField(
            model_name='servicootimizado',
            name='sistema_solicitacao',
            field=models.CharField(blank=True, help_text='Sistema onde o serviço é solicitado (SEI, ColabGov, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='servicootimizado',
            name='tipos_atendimento',
            field=models.JSONField(default=list, help_text='Tipos de atendimento disponíveis (presencial, online, telefone, etc.)'),
        ),
    ]
