# Generated by Django 5.2.6 on 2026-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_assunto_carta_utilizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaooficio',
            name='brasao_largura_cm',
            field=models.DecimalField(decimal_places=2, default=2.8, max_digits=4),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='rodape_protocolo_altura_cm',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Área reservada no rodapé para protocolo digital.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_entrada_etapa',
            field=models.DateTimeField(blank=True, help_text='Momento em que a demanda entrou no status/etapa atual (temporizador de parada).', null=True),
        ),
        migrations.AlterField(
            model_name='servicootimizado',
            name='sistema_solicitacao',
            field=models.CharField(blank=True, help_text='Canal de atendimento ao cidadão na carta (ColabGov, portal online, etc.)', max_length=100),
        ),
    ]
