# Generated by Django 5.2.6 on 2026-07-24 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_demanda_acompanhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstudoViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_operacional', models.CharField(choices=[('EXECUTADO', 'Executado'), ('RESPONDIDO_SEM_EXECUCAO', 'Respondido sem execução'), ('ORIENTACAO', 'Somente orientação'), ('PARCIAL', 'Parcialmente executado')], max_length=32)),
                ('motivo_nao_execucao', models.CharField(blank=True, choices=[('ESTUDO_VIABILIDADE', 'Estudo / viabilidade técnica'), ('DEPENDE_INVESTIMENTO', 'Depende de investimento'), ('DEPENDE_LICITACAO', 'Depende de licitação / contratação'), ('DEPENDE_NORMATIVO', 'Depende de norma / legislação'), ('INVIAVEL_TECNICO', 'Inviável técnico no momento'), ('INFORMACIONAL', 'Registro informativo')], default='', max_length=32)),
                ('escopo_geografico', models.TextField(blank=True, help_text='Ex.: município inteiro, bairro X, trecho da Rua Y.')),
                ('parecer_snapshot', models.TextField(blank=True)),
                ('sinapse_orgao_id', models.BigIntegerField(blank=True, null=True)),
                ('pode_retomar', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de estudo e viabilidade',
                'verbose_name_plural': 'Registros de estudo e viabilidade',
            },
        ),
        migrations.RenameIndex(
            model_name='nooperacional',
            new_name='core_nooper_demanda_ab2f5d_idx',
            old_name='core_nooper_demanda_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nooperacional',
            new_name='core_nooper_parent__b50510_idx',
            old_name='core_nooper_parent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nooperacional',
            new_name='core_nooper_sinapse_c75afb_idx',
            old_name='core_nooper_orgao_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pernaoperacional',
            new_name='core_pernao_demanda_20a877_idx',
            old_name='core_perna_demanda_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pernaoperacional',
            new_name='core_pernao_sinapse_23b8e1_idx',
            old_name='core_perna_orgao_status_idx',
        ),
        migrations.AddField(
            model_name='demanda',
            name='escopo_geografico',
            field=models.TextField(blank=True, help_text='Escopo geográfico declarado na conclusão (ex.: município inteiro, bairro).'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='motivo_nao_execucao',
            field=models.CharField(blank=True, default='', help_text='Motivo quando o pedido não foi executado materialmente.', max_length=32),
        ),
        migrations.AddField(
            model_name='demanda',
            name='resultado_operacional',
            field=models.CharField(blank=True, default='', help_text='Resultado da conclusão operacional (executado, sem execução, etc.).', max_length=32),
        ),
        migrations.AddField(
            model_name='demanda',
            name='stand_by_estudo_viabilidade',
            field=models.BooleanField(default=False, help_text='Demanda registrada na base stand-by de estudo e viabilidade.'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='nos_ativos',
            field=models.PositiveIntegerField(default=0, help_text='Nós operacionais abertos (scatter-gather) — contagem denormalizada.'),
        ),
        migrations.AddField(
            model_name='registroestudoviabilidade',
            name='demanda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_estudo_viabilidade', to='core.demanda'),
        ),
        migrations.AddField(
            model_name='registroestudoviabilidade',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_estudo_viabilidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroestudoviabilidade',
            name='unidade_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_estudo_viabilidade', to='core.unidadeadministrativa'),
        ),
        migrations.AddIndex(
            model_name='registroestudoviabilidade',
            index=models.Index(fields=['resultado_operacional'], name='core_regist_resulta_8fb12d_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestudoviabilidade',
            index=models.Index(fields=['motivo_nao_execucao'], name='core_regist_motivo__e6a06d_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestudoviabilidade',
            index=models.Index(fields=['sinapse_orgao_id'], name='core_regist_sinapse_3b0c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestudoviabilidade',
            index=models.Index(fields=['-criado_em'], name='core_regist_criado__a160c8_idx'),
        ),
    ]
