# Generated by Django 5.2.6 on 2026-07-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_assinatura_validacao_gestor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assinaturavalidacaogestor',
            new_name='core_assina_status_1e1c27_idx',
            old_name='core_assina_status_8f3a21_idx',
        ),
    ]
