# Generated by Django 5.2.16 on 2026-07-30 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_tramitacao_editavel_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='protocolo_legislativo',
            field=models.CharField(blank=True, help_text='Nº do ofício (AAAA-NNNN), sequência anual por autor.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TextoPadraoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('DESPACHO', 'Despacho'), ('ANDAMENTO', 'Andamento'), ('DEVOLUTIVA', 'Devolutiva'), ('CONCLUSAO', 'Conclusão'), ('CONCLUSAO_FINAL', 'Conclusão final'), ('RECUSA', 'Recusa'), ('OPERACIONAL', 'Operacional')], default='DESPACHO', max_length=32)),
                ('corpo', models.TextField(help_text='HTML formatado (Quill/Editor).')),
                ('escopo_tipo', models.CharField(choices=[('PROTOCOLO', 'Protocolo'), ('SECRETARIA', 'Secretaria'), ('SETORIAL', 'Setorial'), ('GERAL', 'Geral')], default='GERAL', max_length=16)),
                ('sinapse_orgao_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_padrao_despacho_criados', to=settings.AUTH_USER_MODEL)),
                ('unidade_administrativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_padrao_despacho', to='core.unidadeadministrativa')),
            ],
            options={
                'verbose_name': 'Texto padrão de despacho',
                'verbose_name_plural': 'Textos padrão de despacho',
                'ordering': ['ordem', 'titulo'],
                'indexes': [models.Index(fields=['categoria', 'ativo', 'escopo_tipo'], name='core_textop_categor_7d71fd_idx'), models.Index(fields=['sinapse_orgao_id', 'ativo'], name='core_textop_sinapse_1a9ce6_idx')],
            },
        ),
    ]
