# Generated by Django 5.2.16 on 2026-07-30 17:54

import django.db.models.deletion
from django.db import migrations, models


def copiar_fk_para_m2m(apps, schema_editor):
    TextoPadraoDespacho = apps.get_model("core", "TextoPadraoDespacho")
    for modelo in TextoPadraoDespacho.objects.exclude(unidade_administrativa_id=None):
        modelo.unidades.add(modelo.unidade_administrativa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_texto_padrao_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='textopadraodespacho',
            name='unidades',
            field=models.ManyToManyField(blank=True, help_text='Setores em que o modelo fica disponível. Vazio = todo o órgão/escopo.', related_name='textos_padrao_despacho', to='core.unidadeadministrativa'),
        ),
        migrations.AlterField(
            model_name='textopadraodespacho',
            name='unidade_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_padrao_despacho_legado', to='core.unidadeadministrativa'),
        ),
        migrations.RunPython(copiar_fk_para_m2m, migrations.RunPython.noop),
    ]
